version: '3.8'

services:
  front-react:
    build:
      context: ./frontend_Eventsportify
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend_Eventsportify:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - back-express

  back-express:
    build:
      context: ./backend_Eventsportify
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend_Eventsportify:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/eventsportify?authSource=admin
    # env_file:
    #   - ./backend_Eventsportify/.env
    depends_on:
      - mongo
 
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo-data:
