version: '3.8'

services:
  front-react:
    build:
      context: ./frontend_Eventsportify
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend_Eventsportify:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - back-express

  back-express:
    build:
      context: ./backend_Eventsportify
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend_Eventsportify:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend_Eventsportify/.env
